host: 0.0.0.0
port: 8089

influxdb:
  url: "http://influxdb:8086"
  database: "monitor"

scheduler:
  host: scheduler
  port: 8888

# host: 0.0.0.0
# port: 10089

# influxdb:
#   url: "http://localhost:8086"
#   database: "monitor"

# scheduler:
#   host: localhost
#   port: 8001