host: 0.0.0.0
port: 8089

influxdb:
  # host: "influxdb"
  # port: 8086
  url: "http://127.0.0.1:8086"
  username: "hanglok"
  password: "hanglok8888"
  database: "monitor_server"

scheduler:
  host: localhost
  port: 8001
