// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: monitor.proto

// 包名

package monitor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Monitor_QueryAllTaskInfo_FullMethodName = "/monitor.monitor/QueryAllTaskInfo"
	Monitor_QueryAvgTaskInfo_FullMethodName = "/monitor.monitor/QueryAvgTaskInfo"
)

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorClient interface {
	QueryAllTaskInfo(ctx context.Context, in *QueryAllTaskInfoReq, opts ...grpc.CallOption) (*QueryAllTaskInfoRsp, error)
	QueryAvgTaskInfo(ctx context.Context, in *QueryAvgTaskInfoReq, opts ...grpc.CallOption) (*QueryAvgTaskInfoRsp, error)
}

type monitorClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorClient(cc grpc.ClientConnInterface) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) QueryAllTaskInfo(ctx context.Context, in *QueryAllTaskInfoReq, opts ...grpc.CallOption) (*QueryAllTaskInfoRsp, error) {
	out := new(QueryAllTaskInfoRsp)
	err := c.cc.Invoke(ctx, Monitor_QueryAllTaskInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) QueryAvgTaskInfo(ctx context.Context, in *QueryAvgTaskInfoReq, opts ...grpc.CallOption) (*QueryAvgTaskInfoRsp, error) {
	out := new(QueryAvgTaskInfoRsp)
	err := c.cc.Invoke(ctx, Monitor_QueryAvgTaskInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
// All implementations must embed UnimplementedMonitorServer
// for forward compatibility
type MonitorServer interface {
	QueryAllTaskInfo(context.Context, *QueryAllTaskInfoReq) (*QueryAllTaskInfoRsp, error)
	QueryAvgTaskInfo(context.Context, *QueryAvgTaskInfoReq) (*QueryAvgTaskInfoRsp, error)
	mustEmbedUnimplementedMonitorServer()
}

// UnimplementedMonitorServer must be embedded to have forward compatible implementations.
type UnimplementedMonitorServer struct {
}

func (UnimplementedMonitorServer) QueryAllTaskInfo(context.Context, *QueryAllTaskInfoReq) (*QueryAllTaskInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAllTaskInfo not implemented")
}
func (UnimplementedMonitorServer) QueryAvgTaskInfo(context.Context, *QueryAvgTaskInfoReq) (*QueryAvgTaskInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAvgTaskInfo not implemented")
}
func (UnimplementedMonitorServer) mustEmbedUnimplementedMonitorServer() {}

// UnsafeMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServer will
// result in compilation errors.
type UnsafeMonitorServer interface {
	mustEmbedUnimplementedMonitorServer()
}

func RegisterMonitorServer(s grpc.ServiceRegistrar, srv MonitorServer) {
	s.RegisterService(&Monitor_ServiceDesc, srv)
}

func _Monitor_QueryAllTaskInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTaskInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).QueryAllTaskInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitor_QueryAllTaskInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).QueryAllTaskInfo(ctx, req.(*QueryAllTaskInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_QueryAvgTaskInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAvgTaskInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).QueryAvgTaskInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitor_QueryAvgTaskInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).QueryAvgTaskInfo(ctx, req.(*QueryAvgTaskInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Monitor_ServiceDesc is the grpc.ServiceDesc for Monitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryAllTaskInfo",
			Handler:    _Monitor_QueryAllTaskInfo_Handler,
		},
		{
			MethodName: "QueryAvgTaskInfo",
			Handler:    _Monitor_QueryAvgTaskInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor.proto",
}
